version: '3.7'

services:
  octoprint:
    image: akamensky/octoprint
    ports:
      - 5000:5000
    # devices:
    #  - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - octoprint:/home/octoprint

volumes:
  octoprint: